apiVersion: serving.knative.dev/{{serving-api-version}}
kind: Service
metadata:
  name: subscriber-a
spec:
  template:
    spec:
      containers:
      - image: img:publish-subscribe-channel/cmd/cloud-event-listener.js
