apiVersion: v1
kind: Pod
metadata:
  name: publisher
  namespace: {{namespace}}
spec:
  containers:
  - name: publisher-container
    image: img:publish-subscribe-channel/cmd/cloud-event-publisher.js
